USE p_personalizacion;
CREATE TABLE elements (
id	int(255) auto_increment not null,
user_id	int (255) not null,
name	varchar(255) not null,
description	text not null,
unit_amount	float not null,
unit_measurement float not null,
unit_costprice float not null,
unit_profitpercentage float not null,
unit_price float not null,

surface_measurement varchar(255) not null,
surface_multiple varchar(255) not null,
surface_multiple_amount varchar(255) not null,
surface_height float not null,
surface_width float not null,
surface_layout varchar(255) not null,
surface_article_height float not null,
surface_article_width float not null,
surface_article_layout varchar(255) not null,
surface_itens int not null,
surface_whole varchar(255) not null,
surface_costprice float not null,
surface_profitpercentage float not null,
surface_price float not null,

coil_measurement float not null,
coil_width float not null,
coil_article_height float not null,
coil_article_width float not null,
coil_article_layout varchar(255) not null,
coil_articles_amount float not null,
coil_costprice float not null,
coil_profitpercentage float not null,
coil_price float not null,
favorite varchar(255) not null,
created_at         datetime DEFAULT NULL,
updated_at         datetime DEFAULT NULL,
CONSTRAINT pk_elements PRIMARY KEY (id),
CONSTRAINT fk_elements_user FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE=InnoDb;


USE p_personalizacion;
CREATE TABLE features (
id	int(255) auto_increment not null,
user_id	int (255) not null,
article_id	int (255) not null,
name	varchar(255) not null,
description	text not null,
unit_amount float null,
unit_measurement varchar(255) not null,
unit_costprice float null,
unit_profitpercentage float null,
unit_price float null,
surface_multiple float null,
surface_multiple_amount float null,
surface_height float null,
surface_width float null,
surface_layout varchar(255) not null,
surface_article_height float null,
surface_article_width float null,
surface_article_layout float null,
surface_iten float null,
surface_total_surfaces float null,
surface_whole varchar(255) not null,
surface_surchage_iten float null,
surface_individual_cost float null,
surface_costprice float null,
surface_profitpercentage float null,
surface_price float null,
coil_width float null,
coil_article_height float null,
coil_article_width float null,
coil_article_layout varchar(255) not null,
coil_articles_amount float null,
coil_articles_total_measure float null,
coil_articles_surchage_iten float null,
coil_articles_measured_cost float null,
coil_costprice float null,
coil_profitpercentage float null,
coil_price float null,
favorite varchar(255) not null,
created_at         datetime DEFAULT NULL,
updated_at         datetime DEFAULT NULL,
CONSTRAINT pk_features PRIMARY KEY (id),
CONSTRAINT fk_features_user FOREIGN KEY (user_id) REFERENCES users(id)
CONSTRAINT fk_features_article FOREIGN KEY (article_id) REFERENCES articles(id)
)ENGINE=InnoDb;
